# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.testcycle_api import TestcycleApi


class TestTestcycleApi(unittest.TestCase):
    """ TestcycleApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.testcycle_api.TestcycleApi()

    def tearDown(self):
        pass

    def test_create_cycle(self):
        """
        Test case for create_cycle

        Create a Test Cycle
        """
        pass

    def test_delete_cycle(self):
        """
        Test case for delete_cycle

        Deletes a Test Cycle
        """
        pass

    def test_get_test_cycle(self):
        """
        Test case for get_test_cycle

        Gets a Test Cycle
        """
        pass

    def test_get_test_cycles(self):
        """
        Test case for get_test_cycles

        Gets multiple Test Cycles
        """
        pass

    def test_update_cycle(self):
        """
        Test case for update_cycle

        Updates a Test Cycle
        """
        pass


if __name__ == '__main__':
    unittest.main()
