# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.login_api import LoginApi


class TestLoginApi(unittest.TestCase):
    """ LoginApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.login_api.LoginApi()

    def tearDown(self):
        pass

    def test_post_access_token(self):
        """
        Test case for post_access_token

        Log in
        """
        pass


if __name__ == '__main__':
    unittest.main()
