# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.automation_schedule_creation_api import AutomationScheduleCreationAPI


class TestAutomationScheduleCreationAPI(unittest.TestCase):
    """ AutomationScheduleCreationAPI unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutomationScheduleCreationAPI(self):
        """
        Test AutomationScheduleCreationAPI
        """
        model = swagger_client.models.automation_schedule_creation_api.AutomationScheduleCreationAPI()


if __name__ == '__main__':
    unittest.main()
