# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.objectlink_api import ObjectlinkApi


class TestObjectlinkApi(unittest.TestCase):
    """ ObjectlinkApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.objectlink_api.ObjectlinkApi()

    def tearDown(self):
        pass

    def test_find(self):
        """
        Test case for find

        Gets associated objects of given objects
        """
        pass

    def test_link_artifacts(self):
        """
        Test case for link_artifacts

        Creates links between objects
        """
        pass

    def test_unlink_artifacts(self):
        """
        Test case for unlink_artifacts

        Removes links between objects
        """
        pass


if __name__ == '__main__':
    unittest.main()
