# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.paged_resource_comment_resource import PagedResourceCommentResource


class TestPagedResourceCommentResource(unittest.TestCase):
    """ PagedResourceCommentResource unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagedResourceCommentResource(self):
        """
        Test PagedResourceCommentResource
        """
        model = swagger_client.models.paged_resource_comment_resource.PagedResourceCommentResource()


if __name__ == '__main__':
    unittest.main()
