# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.testcase_api import TestcaseApi


class TestTestcaseApi(unittest.TestCase):
    """ TestcaseApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.testcase_api.TestcaseApi()

    def tearDown(self):
        pass

    def test_add_comment(self):
        """
        Test case for add_comment

        Adds a Comment to a Test Case
        """
        pass

    def test_add_test_step(self):
        """
        Test case for add_test_step

        Creates a Test Step
        """
        pass

    def test_approve_test_case(self):
        """
        Test case for approve_test_case

        Approves a Test Case
        """
        pass

    def test_create_test_case(self):
        """
        Test case for create_test_case

        Creates a Test Case
        """
        pass

    def test_delete_comment(self):
        """
        Test case for delete_comment

        Deletes a Comment of a Test Case
        """
        pass

    def test_delete_test_case(self):
        """
        Test case for delete_test_case

        Deletes a Test Case
        """
        pass

    def test_delete_test_step(self):
        """
        Test case for delete_test_step

        Deletes a Test Step
        """
        pass

    def test_get_comment(self):
        """
        Test case for get_comment

        Gets a Comment of a Test Case
        """
        pass

    def test_get_comments(self):
        """
        Test case for get_comments

        Gets all Comments of a Test Case
        """
        pass

    def test_get_test_case(self):
        """
        Test case for get_test_case

        Gets a Test Case
        """
        pass

    def test_get_test_case_0(self):
        """
        Test case for get_test_case_0

        Gets a version of a Test Case
        """
        pass

    def test_get_test_cases(self):
        """
        Test case for get_test_cases

        Gets multiple Test Cases
        """
        pass

    def test_get_test_step(self):
        """
        Test case for get_test_step

        Gets a Test Step
        """
        pass

    def test_get_test_steps(self):
        """
        Test case for get_test_steps

        Gets Test Steps of a Test Case
        """
        pass

    def test_get_test_steps_by_version(self):
        """
        Test case for get_test_steps_by_version

        Gets Test Steps of a Test Case version
        """
        pass

    def test_get_versions(self):
        """
        Test case for get_versions

        Gets all versions of a Test Case
        """
        pass

    def test_update_comment(self):
        """
        Test case for update_comment

        Updates a Comment of a Test Case
        """
        pass

    def test_update_test_case(self):
        """
        Test case for update_test_case

        Updates a Test Case
        """
        pass

    def test_update_test_step(self):
        """
        Test case for update_test_step

        Update a Test Step
        """
        pass


if __name__ == '__main__':
    unittest.main()
