# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """ SearchApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.search_api.SearchApi()

    def tearDown(self):
        pass

    def test_query_histories(self):
        """
        Test case for query_histories

        Queries objects' histories
        """
        pass

    def test_search(self):
        """
        Test case for search

        Queries Comments
        """
        pass

    def test_search_0(self):
        """
        Test case for search_0

        Queries objects
        """
        pass


if __name__ == '__main__':
    unittest.main()
