# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.attachment_api import AttachmentApi


class TestAttachmentApi(unittest.TestCase):
    """ AttachmentApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.attachment_api.AttachmentApi()

    def tearDown(self):
        pass

    def test_delete(self):
        """
        Test case for delete

        Deletes an Attachment from an Object
        """
        pass

    def test_get_attachment(self):
        """
        Test case for get_attachment

        Gets an Attachment of an Object
        """
        pass

    def test_get_attachments_of(self):
        """
        Test case for get_attachments_of

        Gets all Attachments of an Object
        """
        pass

    def test_search(self):
        """
        Test case for search

        Searches for Attachments
        """
        pass

    def test_upload(self):
        """
        Test case for upload

        Uploads an Attachment to an Object
        """
        pass


if __name__ == '__main__':
    unittest.main()
