# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """ UserApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.user_api.UserApi()

    def tearDown(self):
        pass

    def test_assign_to_project(self):
        """
        Test case for assign_to_project

        Assigns a User to a Project
        """
        pass

    def test_assign_users_to_project(self):
        """
        Test case for assign_users_to_project

        Assigns multiple Users to a Project
        """
        pass

    def test_create_user(self):
        """
        Test case for create_user

        Invites a User
        """
        pass

    def test_find_by_user_name_or_email(self):
        """
        Test case for find_by_user_name_or_email

        Queries Users by Username
        """
        pass

    def test_find_users_by_projects_name(self):
        """
        Test case for find_users_by_projects_name

        Queries Users by Project Name
        """
        pass

    def test_get_avatar(self):
        """
        Test case for get_avatar

        Gets a User's Avatar
        """
        pass

    def test_get_user_by_id(self):
        """
        Test case for get_user_by_id

        Gets a User
        """
        pass

    def test_reevaluate_token(self):
        """
        Test case for reevaluate_token

        Gets current user's information
        """
        pass


if __name__ == '__main__':
    unittest.main()
