# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.testrun_api import TestrunApi


class TestTestrunApi(unittest.TestCase):
    """ TestrunApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.testrun_api.TestrunApi()

    def tearDown(self):
        pass

    def test_add_comment(self):
        """
        Test case for add_comment

        Adds a Comment to a Test Run
        """
        pass

    def test_create(self):
        """
        Test case for create

        Creates a Test Run
        """
        pass

    def test_delete(self):
        """
        Test case for delete

        Deletes a Test Run
        """
        pass

    def test_delete_comment(self):
        """
        Test case for delete_comment

        Deletes a Comment of a Test Run
        """
        pass

    def test_get(self):
        """
        Test case for get

        Gets a Test Run
        """
        pass

    def test_get_comment(self):
        """
        Test case for get_comment

        Gets a Comment from a Test Run
        """
        pass

    def test_get_comments(self):
        """
        Test case for get_comments

        Gets all Comments of a Test Run
        """
        pass

    def test_get_of(self):
        """
        Test case for get_of

        Gets multiple Test Runs
        """
        pass

    def test_get_status_valuable(self):
        """
        Test case for get_status_valuable

        Gets Test Run statuses
        """
        pass

    def test_update(self):
        """
        Test case for update

        Updates a Test Run
        """
        pass

    def test_update_comment(self):
        """
        Test case for update_comment

        Updates a Comment of a Test Run
        """
        pass


if __name__ == '__main__':
    unittest.main()
