# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.automationjob_api import AutomationjobApi


class TestAutomationjobApi(unittest.TestCase):
    """ AutomationjobApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.automationjob_api.AutomationjobApi()

    def tearDown(self):
        pass

    def test_create_schedule(self):
        """
        Test case for create_schedule

        Create a Schedule
        """
        pass


if __name__ == '__main__':
    unittest.main()
