# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.search_user_response import SearchUserResponse


class TestSearchUserResponse(unittest.TestCase):
    """ SearchUserResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchUserResponse(self):
        """
        Test SearchUserResponse
        """
        model = swagger_client.models.search_user_response.SearchUserResponse()


if __name__ == '__main__':
    unittest.main()
