# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.userprofile_api import UserprofileApi


class TestUserprofileApi(unittest.TestCase):
    """ UserprofileApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.userprofile_api.UserprofileApi()

    def tearDown(self):
        pass

    def test_batch_assign_user_profile_in_client(self):
        """
        Test case for batch_assign_user_profile_in_client

        Assigns multiple Users to a Profile
        """
        pass

    def test_batch_assign_user_profile_in_project(self):
        """
        Test case for batch_assign_user_profile_in_project

        Assigns multiple Users to a Profile in a Project
        """
        pass

    def test_get_current(self):
        """
        Test case for get_current

        Gets current User's Admin Profile
        """
        pass

    def test_get_profiles_of_current_user(self):
        """
        Test case for get_profiles_of_current_user

        Gets current User's Profiles in different Projects
        """
        pass

    def test_get_user_profiles(self):
        """
        Test case for get_user_profiles

        Gets available Profiles
        """
        pass


if __name__ == '__main__':
    unittest.main()
