# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AttachmentAuthor(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, email=None, first_name=None, last_name=None):
        """
        AttachmentAuthor - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'email': 'str',
            'first_name': 'str',
            'last_name': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'email': 'email',
            'first_name': 'first_name',
            'last_name': 'last_name'
        }

        self._id = id
        self._email = email
        self._first_name = first_name
        self._last_name = last_name

    @property
    def id(self):
        """
        Gets the id of this AttachmentAuthor.
        ID of the User

        :return: The id of this AttachmentAuthor.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this AttachmentAuthor.
        ID of the User

        :param id: The id of this AttachmentAuthor.
        :type: int
        """

        self._id = id

    @property
    def email(self):
        """
        Gets the email of this AttachmentAuthor.
        Login username of the User

        :return: The email of this AttachmentAuthor.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this AttachmentAuthor.
        Login username of the User

        :param email: The email of this AttachmentAuthor.
        :type: str
        """

        self._email = email

    @property
    def first_name(self):
        """
        Gets the first_name of this AttachmentAuthor.
        First name of the User

        :return: The first_name of this AttachmentAuthor.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this AttachmentAuthor.
        First name of the User

        :param first_name: The first_name of this AttachmentAuthor.
        :type: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """
        Gets the last_name of this AttachmentAuthor.
        Last name of the User

        :return: The last_name of this AttachmentAuthor.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this AttachmentAuthor.
        Last name of the User

        :param last_name: The last_name of this AttachmentAuthor.
        :type: str
        """

        self._last_name = last_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AttachmentAuthor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
