# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DefectFieldMapping(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, field=None, qtest_fields=None):
        """
        DefectFieldMapping - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'field': 'str',
            'qtest_fields': 'list[str]'
        }

        self.attribute_map = {
            'field': 'field',
            'qtest_fields': 'qtest_fields'
        }

        self._field = field
        self._qtest_fields = qtest_fields

    @property
    def field(self):
        """
        Gets the field of this DefectFieldMapping.
        External tracker Defect's field

        :return: The field of this DefectFieldMapping.
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """
        Sets the field of this DefectFieldMapping.
        External tracker Defect's field

        :param field: The field of this DefectFieldMapping.
        :type: str
        """

        self._field = field

    @property
    def qtest_fields(self):
        """
        Gets the qtest_fields of this DefectFieldMapping.
        qTest Defect's field

        :return: The qtest_fields of this DefectFieldMapping.
        :rtype: list[str]
        """
        return self._qtest_fields

    @qtest_fields.setter
    def qtest_fields(self, qtest_fields):
        """
        Sets the qtest_fields of this DefectFieldMapping.
        qTest Defect's field

        :param qtest_fields: The qtest_fields of this DefectFieldMapping.
        :type: list[str]
        """

        self._qtest_fields = qtest_fields

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DefectFieldMapping):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
