# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TestRunListResource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, links=None, page=None, page_size=None, total=None, items=None):
        """
        TestRunListResource - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'links': 'list[Link]',
            'page': 'int',
            'page_size': 'int',
            'total': 'int',
            'items': 'list[TestRunWithCustomFieldResource]'
        }

        self.attribute_map = {
            'links': 'links',
            'page': 'page',
            'page_size': 'page_size',
            'total': 'total',
            'items': 'items'
        }

        self._links = links
        self._page = page
        self._page_size = page_size
        self._total = total
        self._items = items

    @property
    def links(self):
        """
        Gets the links of this TestRunListResource.

        :return: The links of this TestRunListResource.
        :rtype: list[Link]
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this TestRunListResource.

        :param links: The links of this TestRunListResource.
        :type: list[Link]
        """

        self._links = links

    @property
    def page(self):
        """
        Gets the page of this TestRunListResource.

        :return: The page of this TestRunListResource.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """
        Sets the page of this TestRunListResource.

        :param page: The page of this TestRunListResource.
        :type: int
        """

        self._page = page

    @property
    def page_size(self):
        """
        Gets the page_size of this TestRunListResource.

        :return: The page_size of this TestRunListResource.
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """
        Sets the page_size of this TestRunListResource.

        :param page_size: The page_size of this TestRunListResource.
        :type: int
        """

        self._page_size = page_size

    @property
    def total(self):
        """
        Gets the total of this TestRunListResource.

        :return: The total of this TestRunListResource.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this TestRunListResource.

        :param total: The total of this TestRunListResource.
        :type: int
        """

        self._total = total

    @property
    def items(self):
        """
        Gets the items of this TestRunListResource.

        :return: The items of this TestRunListResource.
        :rtype: list[TestRunWithCustomFieldResource]
        """
        return self._items

    @items.setter
    def items(self, items):
        """
        Sets the items of this TestRunListResource.

        :param items: The items of this TestRunListResource.
        :type: list[TestRunWithCustomFieldResource]
        """

        self._items = items

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TestRunListResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
