# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TestRunWithCustomFieldResource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, parent_id=None, parent_type=None, created=None, links=None, id=None, name=None, order=None, pid=None, properties=None, test_case=None, test_case_version_id=None, creator_id=None):
        """
        TestRunWithCustomFieldResource - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'parent_id': 'int',
            'parent_type': 'str',
            'created': 'datetime',
            'links': 'list[Link]',
            'id': 'int',
            'name': 'str',
            'order': 'int',
            'pid': 'str',
            'properties': 'list[PropertyResource]',
            'test_case': 'TestCaseWithCustomFieldResource',
            'test_case_version_id': 'int',
            'creator_id': 'int'
        }

        self.attribute_map = {
            'parent_id': 'parentId',
            'parent_type': 'parentType',
            'created': 'created',
            'links': 'links',
            'id': 'id',
            'name': 'name',
            'order': 'order',
            'pid': 'pid',
            'properties': 'properties',
            'test_case': 'test_case',
            'test_case_version_id': 'test_case_version_id',
            'creator_id': 'creator_id'
        }

        self._parent_id = parent_id
        self._parent_type = parent_type
        self._created = created
        self._links = links
        self._id = id
        self._name = name
        self._order = order
        self._pid = pid
        self._properties = properties
        self._test_case = test_case
        self._test_case_version_id = test_case_version_id
        self._creator_id = creator_id

    @property
    def parent_id(self):
        """
        Gets the parent_id of this TestRunWithCustomFieldResource.

        :return: The parent_id of this TestRunWithCustomFieldResource.
        :rtype: int
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """
        Sets the parent_id of this TestRunWithCustomFieldResource.

        :param parent_id: The parent_id of this TestRunWithCustomFieldResource.
        :type: int
        """

        self._parent_id = parent_id

    @property
    def parent_type(self):
        """
        Gets the parent_type of this TestRunWithCustomFieldResource.

        :return: The parent_type of this TestRunWithCustomFieldResource.
        :rtype: str
        """
        return self._parent_type

    @parent_type.setter
    def parent_type(self, parent_type):
        """
        Sets the parent_type of this TestRunWithCustomFieldResource.

        :param parent_type: The parent_type of this TestRunWithCustomFieldResource.
        :type: str
        """
        allowed_values = ["root", "release", "test-cycle", "test-suite"]
        if parent_type not in allowed_values:
            raise ValueError(
                "Invalid value for `parent_type` ({0}), must be one of {1}"
                .format(parent_type, allowed_values)
            )

        self._parent_type = parent_type

    @property
    def created(self):
        """
        Gets the created of this TestRunWithCustomFieldResource.

        :return: The created of this TestRunWithCustomFieldResource.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """
        Sets the created of this TestRunWithCustomFieldResource.

        :param created: The created of this TestRunWithCustomFieldResource.
        :type: datetime
        """

        self._created = created

    @property
    def links(self):
        """
        Gets the links of this TestRunWithCustomFieldResource.

        :return: The links of this TestRunWithCustomFieldResource.
        :rtype: list[Link]
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this TestRunWithCustomFieldResource.

        :param links: The links of this TestRunWithCustomFieldResource.
        :type: list[Link]
        """

        self._links = links

    @property
    def id(self):
        """
        Gets the id of this TestRunWithCustomFieldResource.

        :return: The id of this TestRunWithCustomFieldResource.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this TestRunWithCustomFieldResource.

        :param id: The id of this TestRunWithCustomFieldResource.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this TestRunWithCustomFieldResource.

        :return: The name of this TestRunWithCustomFieldResource.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this TestRunWithCustomFieldResource.

        :param name: The name of this TestRunWithCustomFieldResource.
        :type: str
        """
        if name is not None and len(name) > 500:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `500`")
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")

        self._name = name

    @property
    def order(self):
        """
        Gets the order of this TestRunWithCustomFieldResource.

        :return: The order of this TestRunWithCustomFieldResource.
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """
        Sets the order of this TestRunWithCustomFieldResource.

        :param order: The order of this TestRunWithCustomFieldResource.
        :type: int
        """

        self._order = order

    @property
    def pid(self):
        """
        Gets the pid of this TestRunWithCustomFieldResource.

        :return: The pid of this TestRunWithCustomFieldResource.
        :rtype: str
        """
        return self._pid

    @pid.setter
    def pid(self, pid):
        """
        Sets the pid of this TestRunWithCustomFieldResource.

        :param pid: The pid of this TestRunWithCustomFieldResource.
        :type: str
        """

        self._pid = pid

    @property
    def properties(self):
        """
        Gets the properties of this TestRunWithCustomFieldResource.

        :return: The properties of this TestRunWithCustomFieldResource.
        :rtype: list[PropertyResource]
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """
        Sets the properties of this TestRunWithCustomFieldResource.

        :param properties: The properties of this TestRunWithCustomFieldResource.
        :type: list[PropertyResource]
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")

        self._properties = properties

    @property
    def test_case(self):
        """
        Gets the test_case of this TestRunWithCustomFieldResource.

        :return: The test_case of this TestRunWithCustomFieldResource.
        :rtype: TestCaseWithCustomFieldResource
        """
        return self._test_case

    @test_case.setter
    def test_case(self, test_case):
        """
        Sets the test_case of this TestRunWithCustomFieldResource.

        :param test_case: The test_case of this TestRunWithCustomFieldResource.
        :type: TestCaseWithCustomFieldResource
        """
        if test_case is None:
            raise ValueError("Invalid value for `test_case`, must not be `None`")

        self._test_case = test_case

    @property
    def test_case_version_id(self):
        """
        Gets the test_case_version_id of this TestRunWithCustomFieldResource.

        :return: The test_case_version_id of this TestRunWithCustomFieldResource.
        :rtype: int
        """
        return self._test_case_version_id

    @test_case_version_id.setter
    def test_case_version_id(self, test_case_version_id):
        """
        Sets the test_case_version_id of this TestRunWithCustomFieldResource.

        :param test_case_version_id: The test_case_version_id of this TestRunWithCustomFieldResource.
        :type: int
        """

        self._test_case_version_id = test_case_version_id

    @property
    def creator_id(self):
        """
        Gets the creator_id of this TestRunWithCustomFieldResource.

        :return: The creator_id of this TestRunWithCustomFieldResource.
        :rtype: int
        """
        return self._creator_id

    @creator_id.setter
    def creator_id(self, creator_id):
        """
        Sets the creator_id of this TestRunWithCustomFieldResource.

        :param creator_id: The creator_id of this TestRunWithCustomFieldResource.
        :type: int
        """

        self._creator_id = creator_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TestRunWithCustomFieldResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
