# coding: utf-8

"""
    qTest Manager API Version 8.6 - 9.0

    qTest Manager API Version 8.6 - 9.0

    OpenAPI spec version: 8.6 - 9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TestCasePermission(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, create=False, edit=False, delete=False, view=False, edit_assignment=False, export=False, _import=False, approve=False):
        """
        TestCasePermission - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'create': 'bool',
            'edit': 'bool',
            'delete': 'bool',
            'view': 'bool',
            'edit_assignment': 'bool',
            'export': 'bool',
            '_import': 'bool',
            'approve': 'bool'
        }

        self.attribute_map = {
            'create': 'create',
            'edit': 'edit',
            'delete': 'delete',
            'view': 'view',
            'edit_assignment': 'edit_assignment',
            'export': 'export',
            '_import': 'import',
            'approve': 'approve'
        }

        self._create = create
        self._edit = edit
        self._delete = delete
        self._view = view
        self._edit_assignment = edit_assignment
        self._export = export
        self.__import = _import
        self._approve = approve

    @property
    def create(self):
        """
        Gets the create of this TestCasePermission.
        Can create Test Case

        :return: The create of this TestCasePermission.
        :rtype: bool
        """
        return self._create

    @create.setter
    def create(self, create):
        """
        Sets the create of this TestCasePermission.
        Can create Test Case

        :param create: The create of this TestCasePermission.
        :type: bool
        """

        self._create = create

    @property
    def edit(self):
        """
        Gets the edit of this TestCasePermission.
        Can edit Test Case

        :return: The edit of this TestCasePermission.
        :rtype: bool
        """
        return self._edit

    @edit.setter
    def edit(self, edit):
        """
        Sets the edit of this TestCasePermission.
        Can edit Test Case

        :param edit: The edit of this TestCasePermission.
        :type: bool
        """

        self._edit = edit

    @property
    def delete(self):
        """
        Gets the delete of this TestCasePermission.
        Can delete Test Case

        :return: The delete of this TestCasePermission.
        :rtype: bool
        """
        return self._delete

    @delete.setter
    def delete(self, delete):
        """
        Sets the delete of this TestCasePermission.
        Can delete Test Case

        :param delete: The delete of this TestCasePermission.
        :type: bool
        """

        self._delete = delete

    @property
    def view(self):
        """
        Gets the view of this TestCasePermission.
        Can view Test Case

        :return: The view of this TestCasePermission.
        :rtype: bool
        """
        return self._view

    @view.setter
    def view(self, view):
        """
        Sets the view of this TestCasePermission.
        Can view Test Case

        :param view: The view of this TestCasePermission.
        :type: bool
        """

        self._view = view

    @property
    def edit_assignment(self):
        """
        Gets the edit_assignment of this TestCasePermission.
        Can assign Test Case

        :return: The edit_assignment of this TestCasePermission.
        :rtype: bool
        """
        return self._edit_assignment

    @edit_assignment.setter
    def edit_assignment(self, edit_assignment):
        """
        Sets the edit_assignment of this TestCasePermission.
        Can assign Test Case

        :param edit_assignment: The edit_assignment of this TestCasePermission.
        :type: bool
        """

        self._edit_assignment = edit_assignment

    @property
    def export(self):
        """
        Gets the export of this TestCasePermission.
        Can export Test Case

        :return: The export of this TestCasePermission.
        :rtype: bool
        """
        return self._export

    @export.setter
    def export(self, export):
        """
        Sets the export of this TestCasePermission.
        Can export Test Case

        :param export: The export of this TestCasePermission.
        :type: bool
        """

        self._export = export

    @property
    def _import(self):
        """
        Gets the _import of this TestCasePermission.
        Can import Test Case

        :return: The _import of this TestCasePermission.
        :rtype: bool
        """
        return self.__import

    @_import.setter
    def _import(self, _import):
        """
        Sets the _import of this TestCasePermission.
        Can import Test Case

        :param _import: The _import of this TestCasePermission.
        :type: bool
        """

        self.__import = _import

    @property
    def approve(self):
        """
        Gets the approve of this TestCasePermission.
        Can approve Test Case

        :return: The approve of this TestCasePermission.
        :rtype: bool
        """
        return self._approve

    @approve.setter
    def approve(self, approve):
        """
        Sets the approve of this TestCasePermission.
        Can approve Test Case

        :param approve: The approve of this TestCasePermission.
        :type: bool
        """

        self._approve = approve

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TestCasePermission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
